services:
  db:
    image: bitnami/mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    restart: on-failure
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - ALLOW_EMPTY_PASSWORD=yes
